version: '3'
services:
  logiquiz-front-prod:
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
      args:
        - IMAGE_TAG=${IMAGE_TAG}
    image: 'logiquiz-front-prod:${IMAGE_TAG}'
    ports:
      - '3019:3019'
    environment:
      - NODE_ENV=production
